# See README.md for introduction.

services:
  rabbitmq:
    # Stable version with management UI.
    image: rabbitmq:4.2-management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"   # Default RabbitMQ port.
      - "15672:15672" # RabbitMQ management web UI.
    volumes:
      - ./config/rabbit_mq.conf:/etc/rabbitmq/conf.d/rabbit_mq.conf:ro
      - ./config/definitions.json:/etc/rabbitmq/definitions.json:ro
    # This allows to start the gatekeeper service only when rabbitmq is ready
    # to accepts new AMQP connections.  Otherwise gatekeeper will crush after
    # first unsuccessfull connection try.
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      retries: 5
      timeout: 2s
    logging:
      options:
        max-size: "10m"
        max-file: "3"

  mysql:
    build:
      context: .
      dockerfile: ./docker/mysql.Dockerfile
    container_name: mysql
    ports:
      - "3306:3306" # Default MySQL port.
    env_file:
      - ./config/mysql.env
    # This allows to start the justchess service only when mysql is ready
    # to accepts new connections.  Otherwise justchess will crush after
    # first unsuccessfull connection try.
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
      retries: 10
      timeout: 2s
    volumes:
      # Make db data persistent.
      - ./config/mysql.conf:/etc/mysql/conf.d/my.cnf:ro
      - mysql_data:/var/lib/mysql
    logging:
      options:
        max-size: "10m"
        max-file: "3"

  gatekeeper:
    build:
      context: .
      dockerfile: ./docker/gatekeeper.Dockerfile
    container_name: gatekeeper
    env_file:
      - ./config/gatekeeper.env
    depends_on:
      rabbitmq:
        condition: service_healthy
    ports:
      - "3503:3503"                  # Gatekeeper port.
    volumes:
      - ./repo/gatekeeper:/app/src   # Mount source code from host OS.
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    stop_grace_period: 1s
    entrypoint: go run cmd/gatekeeper/main.go

  justchess:
    build:
      context: .
      dockerfile: ./docker/justchess.Dockerfile
    container_name: justchess
    env_file:
      - ./config/justchess.env
    depends_on:
      mysql:
        condition: service_healthy
      gatekeeper:
        condition: service_started
    ports:
      - "3502:3502"                  # Justchess port.
    volumes:
      - ./repo/justchess:/app/src    # Mount source code from host OS.
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    stop_grace_period: 1s
    entrypoint: go run cmd/justchess/main.go

  # Disposable MySQL container to create an isolated test environment.
  testdb:
    build:
      context: .
      dockerfile: ./docker/mysql.Dockerfile
    container_name: testdb
    env_file:
      - ./config/testdb.env
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
      retries: 4
      timeout: 2s
    ports:
      - "52000:52000"

  frontend:
    build:
      context: .
      dockerfile: ./docker/frontend.Dockerfile
    container_name: frontend
    env_file:
      - ./config/frontend.env
    ports:
      - "3000:3000"                     # Default NextJS port.
    volumes:
      - ./repo/frontend/app:/frontend/app        # Mount source code from host OS.
      - ./repo/frontend/public:/frontend/public  # Mount static assets.
    entrypoint: pnpm dev
    logging:
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  mysql_data: