services:
  mysql:
    build:
      context: .
      dockerfile: ./docker/mysql.Dockerfile
    container_name: mysql
    ports:
      # Default MySQL port.
      - "3306:3306"
    env_file:
      - ./config/mysql.env
    # This allows to start the justchess service only when mysql is ready
    # to accepts new connections.  Otherwise justchess will crush after
    # first unsuccessfull connection try.
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
      retries: 10
      timeout: 2s
    volumes:
      # Make db data persistent.
      - ./config/mysql.conf:/etc/mysql/conf.d/my.cnf:ro
      - mysql_data:/var/lib/mysql
    logging:
      options:
        max-size: "10m"
        max-file: "3"

  justchess:
    build:
      context: .
      dockerfile: ./docker/justchess.Dockerfile
    container_name: justchess
    env_file:
      - ./config/justchess.env
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "3502:3502"
    volumes:
      # Mount source code from host OS.
      - ./repo/justchess:/app/src
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    stop_grace_period: 1s
    entrypoint: go run cmd/justchess/main.go

  # Disposable MySQL container to create an isolated test environment.
  testdb:
    build:
      context: .
      dockerfile: ./docker/mysql.Dockerfile
    container_name: testdb
    env_file:
      - ./config/testdb.env
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
      retries: 4
      timeout: 2s
    ports:
      - "52000:52000"

volumes:
  mysql_data:
